foreground         #c4c3c2
backgroundrgb(0, 0, 0)
background_opacity 0.80
cursor             #c4c3c2

active_tab_foreground     #13120d
active_tab_background     #c4c3c2
inactive_tab_foreground   #c4c3c2
inactive_tab_background   #13120d

active_border_color   #c4c3c2
inactive_border_color #13120d
bell_border_color     #3b4e42
font_size 17
